openapi: 3.0.1

info:
  title: ms-banking-customers-api
  description: API for ms-banking-customers
  version: 1.0.0
servers:
  - url: https://localhost:8092
tags:
  - name: ms-banking-customers-api
    description: API for ms-banking-customers
paths:
  /customers:
    get:
      summary: Retrieve all customers
      operationId: retrieveAllCustomers
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customers'
    post:
      summary: Save new customer
      operationId: saveCustomer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerDTO'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomerDTO"
    put:
      summary: Update an existing customer
      operationId: updateCustomer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerDTO'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomerDTO"
  /customers/{id}:
    parameters:
      - name: id
        in: path
        required: true
        description: customer ID
        schema:
          type: integer
          format: int64
          minimum: 1
    get:
      summary: Retrieve a customer
      operationId: retrieveCustomer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomerDTO"
    delete:
      summary: Delete a customer
      operationId: deleteCustomer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomerDTO"
components:
  schemas:
    Customers:
      type: array
      items:
        $ref: "#/components/schemas/CustomerDTO"
    CustomerDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        customerType:
          type: string
        name:
          type: string
        docType:
          type: string
        docNumber:
          type: string
        createdAt:
          type: string
        address:
          type: string
        phoneNumber:
          type: string
        status:
          type: string
        email:
          type: string
        mobilePhoneImeiNumber:
          type: string
        ownedPasiveProductsQty:
          type: integer
        ownedActiveProductsQty:
          type: integer
      required:
        - id
        - customerType
        - name
        - docType
        - docNumber